author: "Tobe O <thosakwe@gmail.com>"
description: "Dart port of ua-parser."
homepage: "https://github.com/thosakwe/uap-dart.git"
name: "ua_parser"
version: "1.0.0"
dev_dependencies: 
  grinder: "^0.8.0+3"
  test: "^0.12.17+2"
  yaml: "^2.1.12"
